name: Checks

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mfisherman/openmpi:5.0.8
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix permissions
        run: |
          chown -R root:root $GITHUB_WORKSPACE
          chmod -R 777 $GITHUB_WORKSPACE

      - name: Install system deps
        run: |
          apt-get update
          apt-get install -y python3 python3-pip python3-venv

      - name: Install uv
        run: pip3 install uv==0.7.15

      - name: Sync dependencies
        run: uv sync

      - name: Print dependencies
        run: uv pip list

      - name: Run basedpyright
        run: uv run basedpyright

      - name: Run ruff lint
        run: uv run ruff check --fix-only .

      - name: Run ruff format
        run: uv run ruff format .

      - name: Install MPI for tests
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: openmpi

      - name: Run tests
        run: uv run pytest tests/ --runslow --durations=10
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
