name: Checks

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: mfisherman/openmpi:5.0.8
      options: --user 1001:1001  # run container as GitHub Actions user to avoid permission issues

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix permissions
        run: chown -R $(id -u):$(id -g) $GITHUB_WORKSPACE

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.15"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync

      - name: Print dependencies
        run: uv pip list

      - name: Run type checks
        run: uv run basedpyright

      - name: Run lint checks
        run: uv run ruff check --fix-only .

      - name: Format code
        run: uv run ruff format .

      - name: Run tests
        run: uv run python -m pytest tests/ --runslow --durations=10
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
